name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django
        pwd
    
    - name: Run Server
      run: | 
        cd Source 
        python manage.py runserver  

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "L00171104@atu.ie"
        git config --global user.name "PratikShelke-1"
        git checkout gh-pages
        git pull origin gh-pages
        cp -r your_static_directory/* .
        git add .
        git commit -m "Update GitHub Pages"
        git push origin gh-pages


